---
- hosts: all
  vars:
    aegir_frontend_url: valkyrie.local
    valkyrie_modules:
      - hosting_alias
      - hosting_civicrm
      - hosting_site_reinstall
      - hosting_valkyrie
    valkyrie_generate_deploy_keys: False
    aegir_fix_ownership: true
    aegir_fix_permissions: true
    aegir_registry_rebuild: true

  pre_tasks:

    - name: Allow Aegir makefile to be overridden by local Valkyrie makefile.
      set_fact:
        aegir_makefile: "{{ item }}"
      with_first_found:
        - /vagrant/valkyrie.make.yml
        - /vagrant/valkyrie.make
        - /vagrant/.valkyrie/valkyrie/vagrant/ansible/roles/getvalkyrie.valkyrie/files/valkyrie.make

#    - name: Create 'aegir' user to map to host user
#      user:
#        name: aegir
#        uid: "{{ host_uid }}"
  roles:
    - geerlingguy.mysql
    - ergonlogic.aegir
    - ergonlogic.skynet
    - getvalkyrie.valkyrie
